### ISSUE TITLE
SDK 5 -> 6: Missing properties?

### ISSUE THREAD

**Issue by hansemannn** [RevenueCat/purchases-android#1020]
**Describe the bug**
We noticed that some important properties are missing in the `StoreProduct` after migrating to RC 6.x:

- `introductoryPriceAmountMicros`
- `introductoryPrice`
- `introductoryPricePeriod`
- `freeTrialPeriod`
- `priceCurrencyCode`

Were these removed by Google? And if so, what's their replacement? We switched to the unified StoreProduct to not have these breaking changes, but if there is an upgrade guide, that'd be fine!

1. Environment
   1. Platform: Android
   2. SDK version: 6.1.1
   3. OS version: 13.0
   4. Android Studio version: 2022.2.1

**Comment by mcastany** [comment]
@hansemannn there is a migration guide, here are the changes to the `StoreProduct` - https://github.com/RevenueCat/purchases-android/blob/main/migrations/v6-MIGRATION.md#storeproduct-changes

**Comment by hansemannn** [comment]
Thank you!
