### ISSUE TITLE
Active subscription show up on other phones/account.

### ISSUE THREAD

**Issue by Nyceane** [RevenueCat/purchases-android#149]
implementation 'com.revenuecat.purchases:purchases:3.1.0'

Hey guys, I am getting a seperate issue

I have successfuly made purchases on one account, but it seems that every other account is seeing this purchase for some reason.  I have clearly seperated it.
```

login()
        Purchases.getSharedInstance().setAllowSharingPlayStoreAccount(false);
        Purchases.getSharedInstance().identify(currentUser.getUid());
        Map<String, String> attr = new HashMap<String, String>();
        attr.put("email", currentUser.getEmail());
        attr.put("name", currentUser.getDisplayName());
        Purchases.getSharedInstance().setAttributes(attr);


logout()
        Purchases.getSharedInstance().invalidatePurchaserInfoCache();
        Purchases.getSharedInstance().reset();
        Purchases.getSharedInstance().setAllowSharingPlayStoreAccount(false);
        FirebaseAuth.getInstance().signOut();

```
But whenever I do
```
        Purchases.getSharedInstance().getPurchaserInfo(
                new ReceivePurchaserInfoListener() {
                    @Override
                    public void onReceived(@NonNull PurchaserInfo purchaserInfo) {
                        if(purchaserInfo != null && !purchaserInfo.getEntitlements().getActive().isEmpty())
                        {
                            //This part always shows that active subscription from other phone/account's purchase for some reason.
                        }
                        else
                        {
                            mTxtSubscription.setText(R.string.subscription_inactive);
                        }
                    }

                    @Override
                    public void onError(@NonNull PurchasesError error) {
                        Log.e("Purchases Sample", error.getMessage());
                    }
                }
        );

```

In Customer history it just keeps creating new "Created a new alias" and I am not creating new alias anywhere... what is going on? =/

I have not once used createAlias, this thing is making it very very difficult for me to test right now.  It seems Purchases.getSharedInstance().identify is just constantly creating aliases...  please help ={

**Comment by aboedo** [comment]
Hi! 👋
`identify` [internally calls createAlias](https://github.com/RevenueCat/purchases-android/blob/develop/purchases/src/main/kotlin/com/revenuecat/purchases/IdentityManager.kt#L31) if the user is an anonymous user. 
Although that part is expected, I'm surprised about the fact that the purchase is seen by other users. 
This would only happen if `identify` is called with the same user ID every time. What ID are the users being aliased to? 
Separate question: are you testing on the same device every time or is this across devices?

**Comment by rkotzy** [comment]
Going to close this out due to inactivity.
