### ISSUE TITLE
Pending purchases are undetectable through the SDK

### ISSUE THREAD

**Issue by ubuntudroid** [RevenueCat/purchases-android#160]
version: 3.2.0

I'm currently integrating the SDK into our app. Previously we used BillingClient directly. With Billing client you could detect pending purchases by checking the returned Purchases for `purchase.purchaseState == Purchase.PurchaseState.PENDING`.  This was useful to inform the user, that their purchase was pending and that they need to complete it (e.g. in a store). Sometimes purchases also seemed to be marked as pending for slow payment methods, then the user had to wait a while before the purchase was marked as completed.

With RevenueCat I didn't find a way to check for currently pending purchases. Maybe it's in there, but just missing in the documentation?

**Comment by rkotzy** [comment]
There is an error message in the purchase block `PAYMENT_PENDING` that may help, there isn't a  way to check for current pending purchases through RevenueCat outside of that error message. Maybe you could still interface with BillingClient directly here?

**Comment by ubuntudroid** [comment]
That error is a good first hint, thanks @rkotzy ! :) 

It would be great to get pending purchases at any time via the SDK though - requesting the data from the BillingClient would mean quite a bit of code just for this special case while one of the main reasons for picking RevenueCat is to actually make all this handling transparent to the codebase. Do you plan on integrating a PurchaserInfo.pendingPurchases (or similar) into the SDK anytime soon?

**Comment by jeiting** [comment]
That might be a decent valid use case. I'll rename this ticket and leave it open.

Not something we're likely to get to short term though unfortunately.

**Comment by ByeBai** [comment]
Also running into some issues for my app in regards to this. Current hacky solution is to just "assume" payment is successful when the error code == `PurchasesErrorCode.paymentPendingError` but ideally would prefer a cleaner solution (there's probably a small % of users that are getting the IAP for free - but its a short-term tradeoff).

**Comment by rkotzy** [comment]
The payment pending error indicates that the payment was NOT successful - so you would be giving away this IAP to 100% of these users. There could be an elegant solution here where you grant them 24hour promo access in this event which gives them time to complete the purchase.

To clarify this issue, the SDK will correctly unlock access to pending purchases after payment goes through, but there isn't a way to see which payments are in the pending state through the Purchases SDK. The situation that complicates this is maintaining the correct status 100% server-side, which we always prefer to do. Maybe there's a helper class or extension we could generate to assist with detecting this client-side at least.

**Comment by taquitos** [comment]
Hiya, this issue is pretty old now, and there has been a lot of changes since it was opened. In this case, I think rkotzy answered the question. I'm going to close this out, but feel free to open a new issue with any other bugs you suspect! Also if you have general questions, you should reach out in our community- you'll get a faster response there, too! See https://github.com/RevenueCat/purchases-android/issues/410#issue-1081392434 for more on!

**Comment by mangal-brovitech** [comment]
Hello @taquitos is the solution implemented of how to handle pending purchases in slow test card scenarios?

**Comment by taquitos** [comment]
cc @aboedo
