### ISSUE TITLE
Old billing client library version

### ISSUE THREAD

**Issue by ubuntudroid** [RevenueCat/purchases-android#162]
Purchases library version: 3.2.0

The Purchases library uses `com.android.billingclient:billing:2.0.3` as a dependency which is severely outdated (at least for a system critical library like the one responsible for billing). The current 2.x version is 2.2.1, the latest version is 3.0.0. Release notes can be found [here](https://developer.android.com/google/play/billing/release-notes).

**Comment by vegaro** [comment]
Thanks for reporting this, we have this in our backlog and will be releasing an update soon. It should be easy to upgrade since not many things have changed.

**Comment by vegaro** [comment]
Little update that we are working on this at the moment.

**Comment by vegaro** [comment]
@ubuntudroid https://github.com/RevenueCat/purchases-android/releases/tag/3.3.0 has been released with the new billing client
