### ISSUE TITLE
Downgrading subscription with DEFERRED does not indicate the change

### ISSUE THREAD

**Issue by peshkira** [RevenueCat/purchases-android#165]
Purchases Version: **3.2.0**

When downgrading a subscription with `BillingFlowParams.ProrationMode.DEFERRED`, we receive the following error:

```
DEBUG: BillingWrapper purchases failed to update. DebugMessage: . ErrorCode: OK.null
ERROR: There was a problem with the Play Store. | Error updating purchases. DebugMessage: . ErrorCode: OK.
```

Within the android billing popup, we see a success checkmark, but immediately after the popup closes, we see the above mentioned error.

The problem is that then the Purchases SDK sometimes reports two active subscriptions and sometimes we only see the old active subscription. In either case they have the flags `willRenew=true` and `isActive=true`.

Technically, it is correct that the old one is still active, but there is no way to see that it will not renew and that there will be another one active after the period ends in order to reflect that in our current UI. There is also no way to be sure that the downgrade was successful due to the error above.

When no proration is passed (null), then the SDK seems to use `UNKNOWN_SUBSCRIPTION_UPGRADE_DOWNGRADE_POLICY` which immediately downgrades the subscription.

Is the problem with the DEFERRED option a bug, or is it not supported, yet? If not supported, are there any plans to support?

Related support discussion: https://docs.revenuecat.com/discuss/5ee8be78ac4d12005c1765bb

**Comment by vegaro** [comment]
@peshkira I have been able to replicate the error but no the two active subscriptions problem. 

For some strange reason the BillingClient returns an empty list of purchases after the success checkmark 🤔 

I will update whenever I find out something else.

(sorry it took so long to reply)

**Comment by vegaro** [comment]
For reference https://github.com/dooboolab/react-native-iap/issues/888 explains the same issue

**Comment by MarkRS-UK** [comment]
Unfortunately it seems that this is not, strictly speaking, an error. That's what Android does, as (eventually) remarked in the thread at the dooboolab link.
Unfortunately, that seems to leave the app with insufficient data to fully confirm the (future) purchase.
The only way I can see to get this working in any way is to record insufficient data and then wait for the Real Time Developer Notification to confirm the rest of the details.
Does anyone see an alternative?

**Comment by peshkira** [comment]
Thanks for the fix. I will try it out soon :)
