### ISSUE TITLE
SharedPreferences gets cleared

### ISSUE THREAD

**Issue by janbolat** [RevenueCat/purchases-android#1663]
Hello,

Our app uses default shared preferences (as many other apps do). The problem is that it gets cleared whenever RevenueCat [clears](https://github.com/RevenueCat/purchases-android/blob/9b9eafdadf681a5ea13430b7e4623b8ee5506c4e/purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/ETagManager.kt#L130) its default [preferences](https://github.com/RevenueCat/purchases-android/blob/9b9eafdadf681a5ea13430b7e4623b8ee5506c4e/purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt#L84). 

Is it possible to make RevenueCat SDK use non-default shared preferences, so that it won't affect the main app?

Right now, I am not able to enable RevenueCat because of this, because whenever I run the app all data in the preferences gets cleared.

Thank you.

**Comment by aboedo** [comment]
@janbolat we don't currently have a way of using non-default shared preferences on Android, but the code should only be erasing the shared preferences strictly used by RevenueCat. 

Unless I'm missing something, the [line you pointed to](https://github.com/RevenueCat/purchases-android/blob/9b9eafdadf681a5ea13430b7e4623b8ee5506c4e/purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/ETagManager.kt#L130) would only apply to the [prefs object within ETagManager](https://github.com/RevenueCat/purchases-android/blob/9b9eafdadf681a5ea13430b7e4623b8ee5506c4e/purchases/src/main/kotlin/com/revenuecat/purchases/common/networking/ETagManager.kt#L53), which gets initialized [with the default value](https://github.com/RevenueCat/purchases-android/blob/main/purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt#L86): 

PurchasesFactory: 
```kotlin
val eTagManager = ETagManager(context)
```

ETagManager initialization: 
<img width="734" alt="image" src="https://github.com/RevenueCat/purchases-android/assets/3922667/6ce46eec-31ca-41f2-a311-9eb8b2d29b58">

<img width="576" alt="image" src="https://github.com/RevenueCat/purchases-android/assets/3922667/fe926237-cb55-40ef-b35b-b6e881de64f3">

So when the line to clear caches is called, it should only be affecting the ones for eTagManager: 
<img width="329" alt="image" src="https://github.com/RevenueCat/purchases-android/assets/3922667/6851f329-1eb4-442b-aed1-8ae96d985f9d">


There's another place where caches are cleared in [DeviceCache](https://github.com/RevenueCat/purchases-android/blob/9b9eafdadf681a5ea13430b7e4623b8ee5506c4e/purchases/src/main/kotlin/com/revenuecat/purchases/common/caching/DeviceCache.kt#L81), but that one also applies changes exclusively to keys used by RevenueCat (which all have a specific prefix). 

<img width="434" alt="image" src="https://github.com/RevenueCat/purchases-android/assets/3922667/c370660e-7867-495d-9601-48b3e1faf8ae">

Any chance something else is going on? 

Tagging @tonidero and @vegaro for fact-checking in case I'm missing something

**Comment by janbolat** [comment]
Thank you for quick response, indeed everything is working fine, even tested on a new sample project. Still investigating... Will get back if I find something...

**Comment by tonidero** [comment]
Thanks @janbolat. Will close this, but feel free to reopen if needed

**Comment by janbolat** [comment]
Is it possible [here](https://github.com/RevenueCat/purchases-android/blob/9b9eafdadf681a5ea13430b7e4623b8ee5506c4e/purchases/src/main/kotlin/com/revenuecat/purchases/PurchasesFactory.kt#L84) to use the passed context itself (but not the application as in the code) ?

**Comment by janbolat** [comment]
Nevermind, I commented out some code in my project to make it work. Thank you
