### ISSUE TITLE
More fine grained permission for linked account in Google API Console

### ISSUE THREAD

**Issue by mikezliu** [RevenueCat/purchases-android#178]
Hi,

My Google Play console is linked to my API project already (google play console only allows 1 linked project), and that API project has some mission critical stuff in it (databases, GCP resources, configuration etc).

Per https://docs.revenuecat.com/docs/creating-play-service-credentials#2-create-service-account, I need to give 'Project Owner' role to the revenuecat service account.

This seems a bit dangerous to me - if that account gets compromised our product could suffer some big outages. Is there more fine grained permissions I can assign to the service account?

**Comment by mikezliu** [comment]
I changed the role to Viewer instead of Owner, and it still seems to work. Are there any side effects I should verify?

**Comment by rkotzy** [comment]
Sorry for the late replay here! You should be fine with the Viewer role now, except to set up Platform Server Notifications you'll need the Pub/Sub Editor role. We've updated our docs with the new minimum permissions, so going to close this out.

https://docs.revenuecat.com/docs/creating-play-service-credentials
