### ISSUE TITLE
NullPointerException In Purchases.onReceiveSkuDetails

### ISSUE THREAD

**Issue by indra452** [RevenueCat/purchases-android#24]
**Library version** : com.revenuecat.purchases:purchases:1.3.1

**Issue :** 

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

com.revenuecat.purchases.Purchases$1$1.onReceiveSkuDetails (Unknown Source:183)
com.revenuecat.purchases.BillingWrapper$2.com.revenuecat.purchases.BillingWrapper$2$1.onSkuDetailsResponse$163bb71f (Unknown Source:13115)
```

In BillingWrapper class, line 115,

`     listener.onReceiveSkuDetails(skuDetailsList);`

skuDetailsList is null sometimes and causes the crash

**Comment by vegaro** [comment]
Closing since  https://github.com/RevenueCat/purchases-android/commit/2d2b7d2434a2c0011628061ff2b2eda131b094a8 should have fix this
