### ISSUE TITLE
Accessing of BillingWrapper#purchasesUpdatedListener is blocking when Purchases is reinitialized

### ISSUE THREAD

**Issue by wilburt** [RevenueCat/purchases-android#246]
**Describe the bug**
It's basically what the title says but here's how to reproduce:

1. Environment
    1. Platform: Android
    2. SDK version: 3.4.1
    3. OS version: Android 10
    4. Android Studio version: 4.1.1
    5. How widespread is the issue. Percentage of devices affected: 100%
2. Steps to reproduce, with a description of expected vs. actual behavior
     1. Initialize the SDK with `Purchases.configure(context, key, appUserId)`
    2. Later, make a purchase with `purchases.purchaseProduct(activity, skuDetails)`
    3. After `onCompleted ` of `MakePurchaseListener` is called,  call `purchases.reset` (and/or `purchases.close`) and reconfigure as in step 1.
   4. Repeat step 2 and the SDK is no longer responsive.
  
I have tracked this down to the lock on the getter for `BillingWrapper#purchasesUpdatedListener` waiting forever.

**Additional context**
We call the functions in step 4 of the reproduction steps during user logout.

**Comment by rkotzy** [comment]
Hey @wilburt 👋. You should only be configuring one instance of the Purchases SDK, and using that shared instance of Purchases throughout the lifecycle of your app (e.g. `Purchases.getSharedInstance().purchasePackage`). It sounds like your configuring one instance of Purchases (P1), then setting up another instance of Purchases (P2) after a purchase is made on P1.

Going to close this out for now unless we can confirm there is a bug.

**Comment by wilburt** [comment]
@rkotzy Thank you for the feedback. Please, what's the right way to handle logout and re-login? Is `Purchases.sharedInstance.reset` (for logout) and `Purchases.sharedInstance.identify` (for relogin) enough?

**Comment by wilburt** [comment]
> @rkotzy Thank you for the feedback. Please, what's the right way to handle logout and re-login? Is `Purchases.sharedInstance.reset` (for logout) and `Purchases.sharedInstance.identify` (for relogin) enough?

Never mind. Seen the docs. Thanks still.

**Comment by rkotzy** [comment]
@wilburt yup - that's it!
