### ISSUE TITLE
RevenueCat new version app crash

### ISSUE THREAD

**Issue by mustafacoskunn** [RevenueCat/purchases-android#332]
1. Environment
   1. Platform: Android
   2. SDK version: 4.2.0
   3. OS version: 10, 8.1.0,6.0.1,7.0
   4. Android Studio version:4.2.1

App crash error

Firebase Crashlytics log
kotlin.collections.CollectionsKt___CollectionsKt.first (CollectionsKt___CollectionsKt.java:222)
com.revenuecat.purchases.Offering.getPackage (Offering.java:82)
com.revenuecat.purchases.Offering.get (Offering.java:68)
com.revenuecat.purchases.Purchases$fetchAndCacheOfferings$1$1$2.invoke (Purchases.java:1195)
com.revenuecat.purchases.Purchases$fetchAndCacheOfferings$1$1$2.invoke (Purchases.java:97)
com.revenuecat.purchases.Purchases.dispatch (Purchases.java:1455)
com.revenuecat.purchases.Purchases.access$dispatch (Purchases.java:97)
com.revenuecat.purchases.Purchases$fetchAndCacheOfferings$1$1.invoke (Purchases.java:1194)
com.revenuecat.purchases.Purchases$fetchAndCacheOfferings$1$1.invoke (Purchases.java:97)
com.revenuecat.purchases.Purchases$getSkuDetails$1$1.invoke (Purchases.java:1411)
com.revenuecat.purchases.Purchases$getSkuDetails$1$1.invoke (Purchases.java:97)
com.revenuecat.purchases.google.BillingWrapper$querySkuDetailsAsync$1$1$1.onSkuDetailsResponse (BillingWrapper.java:154)

**Comment by aboedo** [comment]
hi @mustafacoskunn!! Thanks for reporting! 

From the stack trace, it looks like this it's crashing from the completion block, when trying to access a package by name. Does that seem correct? 

If so, it looks there might be a bug on our side: if you call `offering.getPackage(identifier)` where `identifier` isn't in the list of `availablePackages`, an error will be thrown. 

Could you confirm?

**Comment by aboedo** [comment]
I was able to reproduce by calling `getPackage` with an identifier for a package that isn't available in the `Offering`. 

Since the method can throw, but this behavior isn't actually specified, I added an `@Throws` to make it clear. 
I opened up the following PR https://github.com/RevenueCat/purchases-android/pull/333

Thanks once more for opening!

**Comment by aboedo** [comment]
@mustafacoskunn we've updated the de to make it clear that the method can throw an exception, but we can't update its behavior without affecting others. 
In a future release, we might update this method to make its return `nullable` instead. 

Until then, the best way to handle it is to `try / catch` when calling the method, making sure to catch `NoSuchElementException`.

**Comment by aboedo** [comment]
version 4.3.0 has been released, and it includes the `@Throws` for the method to make it clear that it can throw and that the exception should be handled.

Thanks for reporting!! 🙌
