### ISSUE TITLE
Non consumable products get consumed

### ISSUE THREAD

**Issue by Maradox** [RevenueCat/purchases-android#374]
This is a follow-up to https://github.com/RevenueCat/purchases-android/issues/139.

Is there any progress on this issue/feature? We would like to use revenueCat, but the consumption of products which we don't want to be consumed is holding us back. The alternative of using revenueCat in observer-mode does also not work for us, since the documentation states that in observer-mode entitlements do not work.

**Comment by codykerns** [comment]
Hey @Maradox!

The entitlement system actually does work in Observer Mode - our docs seemed to imply that it wasn't supported, so I updated our documentation to clarify that entitlements will be granted if we pick up on purchases with associated product IDs: https://docs.revenuecat.com/docs/observer-mode#2-sync-purchases-with-revenuecat-android-only

I'll close this out for now, but let me know if you have any other questions.
