### ISSUE TITLE
build fails when adding the Flutter plugin

### ISSUE THREAD

**Issue by arisAlexis** [RevenueCat/purchases-android#421]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [X] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

1. Environment
   1. Platform: Android
   2. SDK version: 30
   3. OS version: Windows
   4. Android Studio version: 2020.3.1
   5. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
1: Task failed with an exception.
-----------
* Where:
Build file 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\purchases_flutter-3.8.0\android\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':purchases_flutter'.
> java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 387

* What went wrong:
A problem occurred configuring project ':purchases_flutter'.
> Failed to notify project evaluation listener.
   > Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt
   > compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Exception: Gradle task assembleDebug failed with exit code 1

3. Steps to reproduce, with a description of expected vs. actual behavior
add flutter plugin according to the docs in project that builds correctly and created by flutter create
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by vegaro** [comment]
Hi @arisAlexis , how are you adding the plugin to your project? Are you using the flutter plugin in an Android app or is your app a Flutter app. I am curious because we have a specific repo for the flutter plugin https://github.com/RevenueCat/purchases-flutter, and this is the repository for the Android library.

**Comment by arisAlexis** [comment]
The flutter plugin has on the requirements only xcode and no instructions for android. I will try opening the ticket there though.
