### ISSUE TITLE
Add Support for Subscription Restoration

### ISSUE THREAD

**Issue by jeiting** [RevenueCat/purchases-android#43]
https://developer.android.com/google/play/billing/billing_subscriptions#restore

**Comment by rkotzy** [comment]
**Update:** We are still working on fully testing a solution for this so our recommendation for now is to opt out by going to:

```Store presence > In-app products > Subscription settings and unchecking "Allow users to restore subscriptions in Google Play"``` 

If you have your own restore functionality implemented through the SDK then things should work if you forget to opt-out but we want to do some more testing first.

**Comment by RajeshKumDev** [comment]
Hi,

Is **restore purchase** added in Revenue Cat Android SDK? 
If yes, can someone provide a documentation link or code snippet.

Thanks.

**Comment by rkotzy** [comment]
@RajeshKumDev you can do a restore from within the SDK with the `restorePurchases` method. There is a snippet in the sample app here:
https://github.com/RevenueCat/purchases-android/blob/3fd3180804f9010fcfe351077df2492bd075e45f/purchases-sample/src/main/java/com/revenuecat/sample/CatsActivity.kt#L25

**Comment by vegaro** [comment]
Closing since this is supported
