### ISSUE TITLE
Error updating purchases. ErrorCode: 6

### ISSUE THREAD

**Issue by scana** [RevenueCat/purchases-android#433]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

**Describe the bug**
We have observed that some of our users that try to buy our product are ending up with the following error:
```
Error updating purchases. DebugMessage: . ErrorCode: 6
```
From what I have seen in Android’s SDK, this points to Play Billing’s API internal error.

Are there any way to mitigate this? 
We have a suspicion that this greatly reduces our conversions rate compared to other means of in-app payments.
Source of the error message: 
https://github.com/RevenueCat/purchases-android/blob/f7fac296913c531dc132b243f17ba0d05922c07b/feature/google/src/main/java/com/revenuecat/purchases/google/BillingWrapper.kt#L523

Environment
   1. Platform: Android
   2. SDK version: 4.6.1
   3. OS version: unknown
   4. Android Studio version: AS Arctic Fox
   5. How widespread is the issue. Percentage of devices affected: 50% of customers that seem to be willing to buy a subscription

Debug logs
Steps to reproduce, with a description of expected vs. actual behavior

The problem is that we cannot reproduce this issue internally, we have noticed it on our dashboards.
We do not have any logcat logs or user reports - we won't be able to provide those without forking RevenueCat's SDK.

 It seems quite severe and it's quite hard for us to figure out how we could mitigate this issue.

**Comment by aboedo** [comment]
Hi! 👋 Thanks for opening! I see that you also have a [ticket in our community](https://community.revenuecat.com/sdks-51/android-sdk-error-updating-purchases-errorcode-6-1035), let's keep the conversation there so it's easier to follow 👍
