### ISSUE TITLE
Null Pointer Exception with HTTP Request

### ISSUE THREAD

**Issue by tfkci** [RevenueCat/purchases-android#471]
- [Yes ] I have updated Purchases SDK to the latest version
- [Yes ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [ yes] I have searched the [Community](https://community.revenuecat.com)
- [yes ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ yes] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

We are following Null Pointer exception with RevenueCat HTTP requests. 

1. Environment
   1. Platform: Android
   2. SDK version: 4.6.1
   3. OS version: All Android versions
   4. Android Studio version: -
   5. How widespread is the issue. %2

2- 

```
com.google.firebase.perf.network.InstrHttpInputStream.close (InstrHttpInputStream.java:67)
arrow_right
com.revenuecat.purchases.common.HTTPClient.performRequest (HTTPClient.kt:113) (This line producers NPE)
com.revenuecat.purchases.common.HTTPClient.performRequest$default (HTTPClient.kt:85)
com.revenuecat.purchases.common.Backend$performRequest$1.call (Backend.kt:63)
com.revenuecat.purchases.common.Dispatcher$AsyncCall.run (Dispatcher.kt:31)
```

3. We are not able to reproduce the issue

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/57030280/152467514-cb9ef6d6-b0f3-4349-a53f-15c2ff388d9f.png">

**Comment by vegaro** [comment]
Thanks for opening @tfkci 

Do you mind sharing the whole stacktrace? 


Line 113 is:

```
            inputStream?.close()
```

Which there's no way produces an NPE since we are null checking... I wonder if the line is not properly being reported in the stacktrace 🤔

**Comment by tfkci** [comment]
I also checked the HTTPClient class, there is no way to create a NPE. 

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/57030280/152554291-e2bf6d71-bfe4-47c0-8cd1-a35d011fb8dd.png">


While the issue is not reproducible on our end. I suspect Firebase Performance Plugin causes the exception while trying to measure network metrics.

**Comment by vegaro** [comment]
Good thinking! Yes that's probably what's happening. This line https://github.com/firebase/firebase-android-sdk/blob/master/firebase-perf/src/main/java/com/google/firebase/perf/network/InstrHttpInputStream.java#L67 could definitely throw an NPE. Not sure how that could happen, maybe the InputStream becomes `null` between our `close` and their `close`?

**Comment by tfkci** [comment]
It is hard to understand their logic, they probably try to use the inputStream after it it is closed.

**Comment by tfkci** [comment]
I created an issue on the Firebase side

https://github.com/firebase/firebase-android-sdk/issues/3406

**Comment by joshdholtz** [comment]
Going to close this issue since it looks like Firebase team took care of catching the potential null pointer on their side! Hit us up this issue revives itself or if anything else comes up 😊
