### ISSUE TITLE
Issue within BillingClient 4.0 - SkuDetails missing freeTrialPeriod

### ISSUE THREAD

**Issue by joshdholtz** [RevenueCat/purchases-android#498]
Google Issue Tracker 👉 https://issuetracker.google.com/issues/219799769?pli=1

There is currently an ongoing issue within BillingClient 4.0 where `freeTrialPeriod` is null which could cause issues within RevenueCat's [Purchases Android](https://github.com/RevenueCat/purchases-android).

This _does_ appear to be inconsistent and fairly rare but could still happen.

We are actively working on getting finding somebody that can address this issue 💪

**Comment by vegaro** [comment]
I am looking into this and there's something quite interesting. This is our current code in `purchases-hybrid-common`:

```
introductoryPricePeriod.mapPeriod()?.let { periodFields ->
            mapOf(
                "price" to introductoryPriceAmountMicros / 1000000.0,
                "priceString" to introductoryPrice,
                "period" to introductoryPricePeriod,
                "cycles" to introductoryPriceCycles
            ) + periodFields
        } ?: null
```        

According to this comment https://github.com/RevenueCat/react-native-purchases/issues/331#issuecomment-1060712979, we send something like:

```
"introPrice": {"cycles": null, "period": null, "periodNumberOfUnits": null, "periodUnit": null, "price": null, "priceString": null}
```

If as we suspect, `introductoryPrice`, `introductoryPricePeriod` and `introductoryPriceCycles` can be returned as null by Google... Why does the response also have `"periodUnit": null` and `"periodNumberOfUnits": null`?. `mapPeriod()` does this:

```
return this.takeUnless { this == null || this.isBlank() }
        ?.let { PurchasesPeriod.parse(it) }
        ?.let { period ->
            when {
                period.years > 0 -> mapOf(
                    "periodUnit" to "YEAR",
                    "periodNumberOfUnits" to period.years
                )
                period.months > 0 -> mapOf(
                    "periodUnit" to "MONTH",
                    "periodNumberOfUnits" to period.months
                )
                period.days > 0 -> mapOf(
                    "periodUnit" to "DAY",
                    "periodNumberOfUnits" to period.days
                )
                else -> mapOf(
                    "periodUnit" to "DAY",
                    "periodNumberOfUnits" to 0
                )
            }
        }
```

There's no way that can return `"periodUnit" to null, "periodNumberOfUnits" to null`

🤔

**Comment by vegaro** [comment]
Not only that, `introductoryPricePeriod.mapPeriod()` would give a NullPointerException if it were to be null

**Comment by taquitos** [comment]
@joshdholtz are there any updates here? I don't have permission to view the linked buginizer 😿

**Comment by NachoSoto** [comment]
BC4 👋🏻
