### ISSUE TITLE
[ANR] [Follow-up] Reported through different file of RevenueCat/purchases-android 

### ISSUE THREAD

**Issue by raghav2945** [RevenueCat/purchases-android#508]
Follow up ticket for : https://github.com/RevenueCat/purchases-android/issues/432#issue-1096941565

Github has locked the open issue, and I am no longer able to communicate with the team on it. So, open a new ticket while referring to the previous one.

@beylmk, The issue is still visible, and we know you dealt with it and are about to share a new SDK version for it. So this is simply a follow-up ticket.

**Comment by vegaro** [comment]
I will unlock the other issue and close this one so it's better organize 👍
