### ISSUE TITLE
Fix link to migration guide

### ISSUE THREAD

**Issue by matteinn** [RevenueCat/purchases-android#515]
- [ ] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

**Describe the bug**

On this [page](https://github.com/RevenueCat/purchases-android/releases/tag/5.0.0) there's a broken link to the migration guide, which should be `https://github.com/RevenueCat/purchases-android/blob/main/migrations/v5-MIGRATION.md` instead of `https://github.com/RevenueCat/purchases-android/blob/5.0.0/%5Bmigrations/v5-MIGRATION.md%5D`.

1. Environment
   1. Platform: Android
   2. SDK version: -
   3. OS version: -
   4. Android Studio version: -
   5. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**
-

**Comment by joshdholtz** [comment]
@matteinn Oops, just took care of updating that! Really appreciate you letting us know 😊
