### ISSUE TITLE
Out Of Memory Error in Dispatcher.java

### ISSUE THREAD

**Issue by sipersso** [RevenueCat/purchases-android#532]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

**Describe the bug**

Posting subscriber attributes crashes the app with an Out of Memory Error. 

1. Environment
   1. Platform: Android 
   2. SDK version: 5.0.0
   3. OS version: 12
   4. Android Studio version:
   5. How widespread is the issue. Percentage of devices affected: Not super common, but it happens
   
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
Here is the stack trace from crashlytics.

```
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
at java.lang.Thread.nativeCreate(Thread.java)
 at java.lang.Thread.start(Thread.java:884)
com.revenuecat.purchases.common.Dispatcher.enqueue (Dispatcher.kt:67)
com.revenuecat.purchases.common.Backend.enqueue (Backend.kt:96)
com.revenuecat.purchases.common.Backend.enqueue$default (Backend.kt:93)
com.revenuecat.purchases.common.Backend.performRequest (Backend.kt:67)
com.revenuecat.purchases.subscriberattributes.SubscriberAttributesPoster.postSubscriberAttributes (SubscriberAttributesPoster.kt:24)
com.revenuecat.purchases.subscriberattributes.SubscriberAttributesManager.synchronizeSubscriberAttributesForAllUsers (SubscriberAttributesManager.kt:62)
com.revenuecat.purchases.Purchases.synchronizeSubscriberAttributesIfNeeded (Purchases.kt:1463)
com.revenuecat.purchases.Purchases.onAppForegrounded (Purchases.kt:206)
com.revenuecat.purchases.AppLifecycleHandler.onMoveToForeground (AppLifecycleHandler.kt:12)
com.revenuecat.purchases.AppLifecycleHandler_LifecycleAdapter.callMethods (AppLifecycleHandler_LifecycleAdapter.java:25)
```

A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

3. Steps to reproduce, with a description of expected vs. actual behavior: 
I am not able to reproduce
 
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

This might be a memory leak? I found a related issue here https://stackoverflow.com/questions/35701501/throwing-outofmemoryerror-pthread-create-1040kb-stack-failed-try-again-when

**Comment by sipersso** [comment]
Looks like this will be closed automatically if I don’t bump it….. so… bump

**Comment by aboedo** [comment]
hey @sipersso!! 👋 Thanks for bumping, I'm sorry we missed this ticket! We'll look into it

**Comment by sipersso** [comment]
Thanks @aboedo 😀

**Comment by vegaro** [comment]
Hi @sipersso ,

I've looked into this a bit and it doesn't seem like we are leaking anything or doing anything that would increase memory usage indiscriminately, so I am a little lost here and I am not sure where else to look.

One thing I wanted to mention though is that our library shares memory with your app, so it's possible there's something in your app that is increasing the memory? It's definitely strange that this only happens when posting subscriber attributes though... Do you have other stacktraces that show another methods being called?

I recommend you https://square.github.io/leakcanary/ to check if your app has any memory leak.
