### ISSUE TITLE
v5.0.0 and Subscriptions API 

### ISSUE THREAD

**Issue by limamauricio** [RevenueCat/purchases-android#537]
_You are using the InAppProduct API, which is no longer updated, to manage subscriptions. Start using the new Subscriptions API to take advantage of new features such as different basic plans and offers as well as prepaid plans._

I got this warning on my console, I would like to know if the newest version already supports this new API. All the old subscriptions were migrated as "read-only" and I would like to know if making them editable would result in any side effects in RevenueCat sdk

**Comment by aboedo** [comment]
Hi! 👋 Thanks for writing in. 

We recently put out a blog post covering Google's new features and our plans to support them. 
https://www.revenuecat.com/blog/google-i-o-2022-announcement/

The TL;DR: is that everything that's marked as "Backwards compatible" will continue to work, and you can edit it too. However, the new features like pre-paid top-ups and pricing phases won't be available through RevenueCat even if they're configured through Google Play. 

We're working on support for the new features, but I don't have an ETA to share just yet. 

In the meantime, you should still be able to modify the old subscriptions. Just make sure that you continue to have no more than one single offer per subscription, and look for the "Backwards compatible" badge. 

Hope this helps!

**Comment by aboedo** [comment]
@limamauricio I'm tentatively closing this issue, but let us know if you have any more questions!
