### ISSUE TITLE
Returning 'Purchase' object instead of sku after purchase is completed

### ISSUE THREAD

**Issue by aldemirenes** [RevenueCat/purchases-android#55]
I think it is much more better to return purchase object instead of just sku in [here](https://github.com/RevenueCat/purchases-android/blob/2.0.1/purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt#L634). Reason is that other infos e.g. signature, originalJson can be needed.

**Comment by rkotzy** [comment]
Fixed here: https://github.com/RevenueCat/purchases-android/pull/57
