### ISSUE TITLE
App crashing on start. Issue started after integrating RevenueCat Version 5.1.1 with Android Billing Client version : 5.0.0.

### ISSUE THREAD

**Issue by kunal228** [RevenueCat/purchases-android#551]
- [ ] I have updated Purchases SDK to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [ ] I have searched the [Community](https://community.revenuecat.com)
- [ ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-android/issues)

**Describe the bug**
App crashing on start. Issue started after integrating RevenueCat Version 5.1.1 with Android Billing Client version : 5.0.0.

1. Environment
   1. Platform: Android 
   2. SDK version: RevenueCat Version 5.1.1
   3. Android Billing Client version : 5.0.0
   4. OS version: Android-11
   5. Android Studio version: Android Studio Bumblebee

2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
    - Fatal Exception: java.lang.NoSuchMethodError
No virtual method queryPurchases(Ljava/lang/String;)Lcom/android/billingclient/api/Purchase$PurchasesResult; in class Lcom/android/billingclient/api/BillingClient; or its super classes (declaration of 'com.android.billingclient.api.BillingClient')

3. Steps to reproduce, with a description of expected vs. actual behavior 
- Just integrated as mentioned in the RevenueCat documentation.

**Additional context**

**Comment by aboedo** [comment]
@kunal228 I'm tentatively closing this ticket, but let me know if you run into any other issues. 
Also, we've updated our android docs to include a note about Billing Client 5 and the new subscriptions model. You can see the [updated docs here](https://docs.revenuecat.com/docs/android-products). 
Have a great day!
