### ISSUE TITLE
 [ANR] Fresh ANR reported from BillingWrapper class

### ISSUE THREAD

**Issue by raghav2945** [RevenueCat/purchases-android#553]
> It looks like there might be instances where Google's `BillingClient.startConnection` simply never finishes, and that's where the connection would entirely fail. 
> 
> This is nearly impossible to reproduce artificially, sadly, but we're trying to think about solutions. 
> 
> It seems from Google's docs [(or the closest thing to it, sadly)](https://github.com/android/play-billing-samples/blob/8f8792fe23e343883984f361a5ecb56e70653911/TrivialDriveKotlin/app/src/main/java/com/sample/android/trivialdrivesample/billing/BillingDataSource.kt#L156) that this should only happen in fairly rare causes, if the Google Play Store self-upgrades or is force closed. 
> 
> Does the volume you're seeing seem to match up with that?
> 
_Originally posted by @aboedo in https://github.com/RevenueCat/purchases-android/issues/524#issuecomment-1112617562_

We have a value to report now that adoption is at its peak. It is close to 400 counts in the last 7 days for only two versions. I believe you should revisit this with your team to see if they can find a workaround.

**Comment by aboedo** [comment]
@raghav2945 Thanks for reporting back!! We'll take another look

**Comment by aboedo** [comment]
[ticket for internal reference](https://revenuecats.atlassian.net/browse/CSDK-302)

**Comment by raghav2945** [comment]
@aboedo, Is there any new update on this? We need to tag our local issue with our release plan; could you please share some plans for its resolution? We must plan accordingly. Thanks !!!

**Comment by raghav2945** [comment]
Thank you so much for @aboedo, for keeping us updated; we greatly appreciate your help. I'll be waiting for more information on the release. I'm hoping that this fix will solve the problem.

**Comment by raghav2945** [comment]
Thank you @aboedo for keeping us updated; we will use it and let you know if we run into any problems. Thank you for your prompt assistance.
