### ISSUE TITLE
getIntroductoryPriceAmountMicros() should return Long

### ISSUE THREAD

**Issue by joluet** [RevenueCat/purchases-android#67]
I think `getIntroductoryPriceAmountMicros()` in `SkuDetails` should return a `Long` value instead of `String`.

Library version: 2.1.2

**Comment by vegaro** [comment]
Thanks for reporting! Unfortunately, `SkuDetails` is part of [BillingClient](https://developer.android.com/reference/com/android/billingclient/api/SkuDetails.html#getIntroductoryPriceAmountMicros()) and we don't have control over it since it's a Google class.

**Comment by vegaro** [comment]
https://developer.android.com/google/play/billing/billing_library_releases_notes#bug_fixes Looks like Google has already fixed this in BillingClient 2.0. Whenever Purchases gets updated to the new version `getIntroductoryPriceAmountMicros` will start returning a long
