### ISSUE TITLE
Cache is cleared on launch if the user is offline

### ISSUE THREAD

**Issue by joluet** [RevenueCat/purchases-android#68]
`Purchases.configure()` invokes `Purchases.identify()` which in turn invokes `updateCaches()`. This will try to update the cache by calling `fetchAndCachePurchaserInfo()`. If the user is offline this will result in a `PurchasesError` and clear the cache. 

This is currently a huge problem for me as it basically breaks the purchase check when the user is offline.

**Comment by jeiting** [comment]
Hey Joluet, what version of the SDK is this?

**Comment by joluet** [comment]
Sorry it's version `2.1.2`. I just tried to implement a workaround and discovered that the cache will also be cleared on every call to `getPurchaserInfo()` while the user is offline.

**Comment by joluet** [comment]
@jeiting I don't think an error should clear the cache here 🤔: 
https://github.com/RevenueCat/purchases-android/blob/99c8aa5b9e4b97c933078c78284a6796aedd4827/purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt#L627-L641

**Comment by jeiting** [comment]
Yeah, I think you might be right. @vegaro is looking into it right now.

**Comment by joluet** [comment]
OK thank you 👍
