### ISSUE TITLE
Crash at com.revenuecat.purchases.Purchases.updatePendingPurchaseQueue$purchases_release (Purchases.kt:872)

### ISSUE THREAD

**Issue by yong0726** [RevenueCat/purchases-android#80]
Hi,

please have a look the below crash.

Version: com.revenuecat.purchases:purchases:2.3.1

Fatal Exception: java.util.concurrent.RejectedExecutionException
Task com.revenuecat.purchases.Purchases$updatePendingPurchaseQueue$1@bbd4877 rejected from java.util.concurrent.ThreadPoolExecutor@eb64ce4[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 11]
com.revenuecat.purchases.Purchases.updatePendingPurchaseQueue$purchases_release

java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution (ThreadPoolExecutor.java:2049)
java.util.concurrent.ThreadPoolExecutor.reject (ThreadPoolExecutor.java:814)
java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1360)
com.revenuecat.purchases.Purchases.updatePendingPurchaseQueue$purchases_release (Purchases.kt:872)
com.revenuecat.purchases.Purchases$2.onConnected (Purchases.kt:131)
com.revenuecat.purchases.BillingWrapper.onBillingSetupFinished (BillingWrapper.kt:308)
com.android.billingclient.api.BillingClientImpl$BillingServiceConnection$1.run (BillingClientImpl.java:1155)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:185)
android.app.ActivityThread.main (ActivityThread.java:6615)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:916)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:806)

**Comment by tonycosentini** [comment]
Hey @yong0726,

Which release are you seeing this in? If it's 2.3.0, can you try and see if it reproduces in 2.3.1?

**Comment by yong0726** [comment]
The version is 2.3.1. it occurs with high frequency in the production.

**Comment by yong0726** [comment]
Hi @vegaro 

May I know when this fix will be released?

**Comment by vegaro** [comment]
@yong0726 It will be released this week
