### ISSUE TITLE
Delayed payments Support

### ISSUE THREAD

**Issue by hvaddi9** [RevenueCat/purchases-android#82]
RevenueCat Version: 2.3.1

All my customer in-app purchases are delayed but successful payments. Hence the purchase perks are all not reflecting on the app. Also, since the purchases are not acknowledged they get refunded after a few days. So I'm manually using billing APIs to acknowledge them with purchase tokens and provide the perks to users from the backend.

Google is even providing two extra test cases in their latest billing library (billingclient:billing:2.0.2).
1. Slow test card, approves after a few minutes
2. Slow test card, declines after a few minutes

Since revenuecat (v2.3.1) uses an older version of Google billing client, how do I handle delayed payments using revenuecat? Is there a proper solution or workaround for this?

**Comment by vegaro** [comment]
Hi, there should be support for this in the latest 3.x.x version. Thanks for reporting!

**Comment by the-habu** [comment]
Please advise what methods to use to do this. I am using purchaseProduct and have no idea how to iterate past product purchases if delayed.
I also asked here, but now I found this Github Issue. https://docs.revenuecat.com/v2.3.0/discuss/5d26824b61f9060044c1498e
Thank you in advance!

**Comment by KevinColemanInc** [comment]
@vegaro Can you link to the documentation describing how to add support for this or does the problem just go away (e.g. `.purchase` does not return until after the delayed payment is finished)?

**Comment by armandojimenez** [comment]
How is this supported?
