### ISSUE TITLE
Upgrade com.android.billingclient:billing to 2.x and enable support for pending purchases

### ISSUE THREAD

**Issue by Sese-Schneider** [RevenueCat/purchases-android#89]
Please update the used billing client from `1.2.2` to `2.x` to keep the library up to date and compatible with other libraries and support pending purchases.

Downgrading as in issue #75 won't work because our app relies on other libraries in flutter.

I'm using version `2.4.0` via [purchases-flutter](https://github.com/RevenueCat/purchases-flutter)

**Comment by vegaro** [comment]
Hi @Sese-Schneider. Thanks for reporting this. We are finalizing some tests on a branch that has the update https://github.com/RevenueCat/purchases-android/pull/88 before we release it to the public.

The Flutter update should be released in the next few weeks. I will keep this opened until the update is released.

**Comment by Sese-Schneider** [comment]
@vegaro are there any recent updates?

**Comment by vegaro** [comment]
Sorry, I forgot to close this. This has been added in 3.x.x and it's also available in Flutter via version 1.x.x. 

Thanks!

**Comment by Nyceane** [comment]
hey guys, is this solved?  I am still having this issue

**Comment by vegaro** [comment]
Yes, this has been solved. What version are you using @Nyceane? Do you have other in app purchases libraries in your app?

**Comment by Nyceane** [comment]
implementation 'com.revenuecat.purchases:purchases:3.1.0'

Adding or Removing     implementation 'com.android.billingclient:billing:2.1.0' doesn't make any difference.
